/* This file was automatically generated by CasADi 3.6.5.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) grad_h_theta_fcn_ ## ID
#endif

#include <math.h>
#include <stdio.h>
#include <string.h>
#ifdef MATLAB_MEX_FILE
#include <mex.h>
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fabs CASADI_PREFIX(fabs)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_from_mex CASADI_PREFIX(from_mex)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sign CASADI_PREFIX(sign)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_to_mex CASADI_PREFIX(to_mex)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_fabs(casadi_real x) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>0 ? x : -x;
#else
  return fabs(x);
#endif
}

casadi_real casadi_sign(casadi_real x) { return x<0 ? -1 : x>0 ? 1 : x;}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

#ifdef MATLAB_MEX_FILE
casadi_real* casadi_from_mex(const mxArray* p, casadi_real* y, const casadi_int* sp, casadi_real* w) {
  casadi_int nrow, ncol, is_sparse, c, k, p_nrow, p_ncol;
  const casadi_int *colind, *row;
  mwIndex *Jc, *Ir;
  const double* p_data;
  if (!mxIsDouble(p) || mxGetNumberOfDimensions(p)!=2)
    mexErrMsgIdAndTxt("Casadi:RuntimeError",
      "\"from_mex\" failed: Not a two-dimensional matrix of double precision.");
  nrow = *sp++;
  ncol = *sp++;
  colind = sp;
  row = sp+ncol+1;
  p_nrow = mxGetM(p);
  p_ncol = mxGetN(p);
  is_sparse = mxIsSparse(p);
  Jc = 0;
  Ir = 0;
  if (is_sparse) {
    Jc = mxGetJc(p);
    Ir = mxGetIr(p);
  }
  p_data = (const double*)mxGetData(p);
  if (p_nrow==1 && p_ncol==1) {
    casadi_int nnz;
    double v = is_sparse && Jc[1]==0 ? 0 : *p_data;
    nnz = sp[ncol];
    casadi_fill(y, nnz, v);
  } else {
    casadi_int tr = 0;
    if (nrow!=p_nrow || ncol!=p_ncol) {
      tr = nrow==p_ncol && ncol==p_nrow && (nrow==1 || ncol==1);
      if (!tr) mexErrMsgIdAndTxt("Casadi:RuntimeError",
                                 "\"from_mex\" failed: Dimension mismatch. "
                                 "Expected %d-by-%d, got %d-by-%d instead.",
                                 nrow, ncol, p_nrow, p_ncol);
    }
    if (is_sparse) {
      if (tr) {
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]+c*nrow]=0;
        for (c=0; c<p_ncol; ++c)
          for (k=Jc[c]; k<(casadi_int) Jc[c+1]; ++k) w[c+Ir[k]*p_ncol] = p_data[k];
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) y[k] = w[row[k]+c*nrow];
      } else {
        for (c=0; c<ncol; ++c) {
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]]=0;
          for (k=Jc[c]; k<(casadi_int) Jc[c+1]; ++k) w[Ir[k]]=p_data[k];
          for (k=colind[c]; k<colind[c+1]; ++k) y[k]=w[row[k]];
        }
      }
    } else {
      for (c=0; c<ncol; ++c) {
        for (k=colind[c]; k<colind[c+1]; ++k) {
          y[k] = p_data[row[k]+c*nrow];
        }
      }
    }
  }
  return y;
}

#endif

#define casadi_to_double(x) ((double) x)

#ifdef MATLAB_MEX_FILE
mxArray* casadi_to_mex(const casadi_int* sp, const casadi_real* x) {
  casadi_int nrow, ncol, c, k;
#ifndef CASADI_MEX_NO_SPARSE
  casadi_int nnz;
#endif
  const casadi_int *colind, *row;
  mxArray *p;
  double *d;
#ifndef CASADI_MEX_NO_SPARSE
  casadi_int i;
  mwIndex *j;
#endif /* CASADI_MEX_NO_SPARSE */
  nrow = *sp++;
  ncol = *sp++;
  colind = sp;
  row = sp+ncol+1;
#ifndef CASADI_MEX_NO_SPARSE
  nnz = sp[ncol];
  if (nnz!=nrow*ncol) {
    p = mxCreateSparse(nrow, ncol, nnz, mxREAL);
    for (i=0, j=mxGetJc(p); i<=ncol; ++i) *j++ = *colind++;
    for (i=0, j=mxGetIr(p); i<nnz; ++i) *j++ = *row++;
    if (x) {
      d = (double*)mxGetData(p);
      for (i=0; i<nnz; ++i) *d++ = casadi_to_double(*x++);
    }
    return p;
  }
#endif /* CASADI_MEX_NO_SPARSE */
  p = mxCreateDoubleMatrix(nrow, ncol, mxREAL);
  if (x) {
    d = (double*)mxGetData(p);
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        d[row[k]+c*nrow] = casadi_to_double(*x++);
      }
    }
  }
  return p;
}

#endif

#ifndef CASADI_PRINTF
#ifdef MATLAB_MEX_FILE
  #define CASADI_PRINTF mexPrintf
#else
  #define CASADI_PRINTF printf
#endif
#endif

static const casadi_int casadi_s0[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s1[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s2[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s3[9] = {1, 3, 0, 1, 2, 3, 0, 0, 0};

/* grad_h_theta_fcn:(i0[4],i1,i2[3],i3,i4,i5,i6,i7)->(o0[1x3]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *ss;
  casadi_real *w0=w+0, *w1=w+3, *w2=w+6, w3, *w4=w+11, w5, w6, w7, w8, w9, w10, w11, w12, w13;
  /* #0: @0 = zeros(3x1) */
  casadi_clear(w0, 3);
  /* #1: @1 = zeros(3x1) */
  casadi_clear(w1, 3);
  /* #2: @2 = input[0][0] */
  casadi_copy(arg[0], 4, w2);
  /* #3: @3 = @2[0] */
  for (rr=(&w3), ss=w2+0; ss!=w2+1; ss+=1) *rr++ = *ss;
  /* #4: @4 = input[2][0] */
  casadi_copy(arg[2], 3, w4);
  /* #5: @5 = @4[2] */
  for (rr=(&w5), ss=w4+2; ss!=w4+3; ss+=1) *rr++ = *ss;
  /* #6: @6 = input[1][0] */
  w6 = arg[1] ? arg[1][0] : 0;
  /* #7: @7 = @2[3] */
  for (rr=(&w7), ss=w2+3; ss!=w2+4; ss+=1) *rr++ = *ss;
  /* #8: @6 = (@6-@7) */
  w6 -= w7;
  /* #9: @5 = (@5*@6) */
  w5 *= w6;
  /* #10: @7 = input[6][0] */
  w7 = arg[6] ? arg[6][0] : 0;
  /* #11: @8 = input[3][0] */
  w8 = arg[3] ? arg[3][0] : 0;
  /* #12: @7 = (@7*@8) */
  w7 *= w8;
  /* #13: @5 = (@5+@7) */
  w5 += w7;
  /* #14: @3 = (@3-@5) */
  w3 -= w5;
  /* #15: @5 = fabs(@3) */
  w5 = casadi_fabs( w3 );
  /* #16: @5 = sqrt(@5) */
  w5 = sqrt( w5 );
  /* #17: @7 = 0.63662 */
  w7 = 6.3661977236758138e-01;
  /* #18: @9 = atan(@3) */
  w9 = atan( w3 );
  /* #19: @9 = (@7*@9) */
  w9  = (w7*w9);
  /* #20: @10 = (@5*@9) */
  w10  = (w5*w9);
  /* #21: @10 = (-@10) */
  w10 = (- w10 );
  /* #22: (@1[0] += @10) */
  for (rr=w1+0, ss=(&w10); rr!=w1+1; rr+=1) *rr += *ss++;
  /* #23: @10 = @2[1] */
  for (rr=(&w10), ss=w2+1; ss!=w2+2; ss+=1) *rr++ = *ss;
  /* #24: @8 = (@8-@10) */
  w8 -= w10;
  /* #25: @10 = input[5][0] */
  w10 = arg[5] ? arg[5][0] : 0;
  /* #26: @8 = (@8*@10) */
  w8 *= w10;
  /* #27: @10 = sign(@3) */
  w10 = casadi_sign( w3 );
  /* #28: @11 = @4[0] */
  for (rr=(&w11), ss=w4+0; ss!=w4+1; ss+=1) *rr++ = *ss;
  /* #29: @9 = (@11*@9) */
  w9  = (w11*w9);
  /* #30: @12 = (2.*@5) */
  w12 = (2.* w5 );
  /* #31: @9 = (@9/@12) */
  w9 /= w12;
  /* #32: @10 = (@10*@9) */
  w10 *= w9;
  /* #33: @10 = (-@10) */
  w10 = (- w10 );
  /* #34: @11 = (@11*@5) */
  w11 *= w5;
  /* #35: @7 = (@7*@11) */
  w7 *= w11;
  /* #36: @11 = 1 */
  w11 = 1.;
  /* #37: @5 = sq(@3) */
  w5 = casadi_sq( w3 );
  /* #38: @11 = (@11+@5) */
  w11 += w5;
  /* #39: @7 = (@7/@11) */
  w7 /= w11;
  /* #40: @10 = (@10-@7) */
  w10 -= w7;
  /* #41: @7 = 100 */
  w7 = 100.;
  /* #42: @11 = 0.63662 */
  w11 = 6.3661977236758138e-01;
  /* #43: @5 = @4[1] */
  for (rr=(&w5), ss=w4+1; ss!=w4+2; ss+=1) *rr++ = *ss;
  /* #44: @9 = input[7][0] */
  w9 = arg[7] ? arg[7][0] : 0;
  /* #45: @5 = (@5*@9) */
  w5 *= w9;
  /* #46: @5 = (@11*@5) */
  w5  = (w11*w5);
  /* #47: @12 = 1 */
  w12 = 1.;
  /* #48: @3 = (@7*@3) */
  w3  = (w7*w3);
  /* #49: @13 = sq(@3) */
  w13 = casadi_sq( w3 );
  /* #50: @12 = (@12+@13) */
  w12 += w13;
  /* #51: @5 = (@5/@12) */
  w5 /= w12;
  /* #52: @7 = (@7*@5) */
  w7 *= w5;
  /* #53: @10 = (@10-@7) */
  w10 -= w7;
  /* #54: @6 = (@6*@10) */
  w6 *= w10;
  /* #55: @8 = (@8-@6) */
  w8 -= w6;
  /* #56: (@1[2] += @8) */
  for (rr=w1+2, ss=(&w8); rr!=w1+3; rr+=1) *rr += *ss++;
  /* #57: @3 = atan(@3) */
  w3 = atan( w3 );
  /* #58: @11 = (@11*@3) */
  w11 *= w3;
  /* #59: @11 = (@11*@9) */
  w11 *= w9;
  /* #60: @11 = (-@11) */
  w11 = (- w11 );
  /* #61: (@1[1] += @11) */
  for (rr=w1+1, ss=(&w11); rr!=w1+2; rr+=1) *rr += *ss++;
  /* #62: @11 = @1[0] */
  for (rr=(&w11), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #63: (@0[0] = @11) */
  for (rr=w0+0, ss=(&w11); rr!=w0+1; rr+=1) *rr = *ss++;
  /* #64: @11 = @1[1] */
  for (rr=(&w11), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #65: (@0[1] = @11) */
  for (rr=w0+1, ss=(&w11); rr!=w0+2; rr+=1) *rr = *ss++;
  /* #66: @11 = @1[2] */
  for (rr=(&w11), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #67: (@0[2] = @11) */
  for (rr=w0+2, ss=(&w11); rr!=w0+3; rr+=1) *rr = *ss++;
  /* #68: output[0][0] = @0 */
  casadi_copy(w0, 3, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int grad_h_theta_fcn(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int grad_h_theta_fcn_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int grad_h_theta_fcn_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void grad_h_theta_fcn_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int grad_h_theta_fcn_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void grad_h_theta_fcn_release(int mem) {
}

CASADI_SYMBOL_EXPORT void grad_h_theta_fcn_incref(void) {
}

CASADI_SYMBOL_EXPORT void grad_h_theta_fcn_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int grad_h_theta_fcn_n_in(void) { return 8;}

CASADI_SYMBOL_EXPORT casadi_int grad_h_theta_fcn_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real grad_h_theta_fcn_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* grad_h_theta_fcn_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    case 6: return "i6";
    case 7: return "i7";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* grad_h_theta_fcn_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* grad_h_theta_fcn_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s1;
    case 4: return casadi_s1;
    case 5: return casadi_s1;
    case 6: return casadi_s1;
    case 7: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* grad_h_theta_fcn_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int grad_h_theta_fcn_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 23;
  return 0;
}

CASADI_SYMBOL_EXPORT int grad_h_theta_fcn_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 23*sizeof(casadi_real);
  return 0;
}

#ifdef MATLAB_MEX_FILE
void mex_grad_h_theta_fcn(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  casadi_int i;
  int mem;
  casadi_real w[39];
  casadi_int *iw = 0;
  const casadi_real* arg[10] = {0};
  casadi_real* res[2] = {0};
  if (argc>8) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"grad_h_theta_fcn\" failed. Too many input arguments (%d, max 8)", argc);
  if (resc>1) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"grad_h_theta_fcn\" failed. Too many output arguments (%d, max 1)", resc);
  if (--argc>=0) arg[0] = casadi_from_mex(argv[0], w, casadi_s0, w+16);
  if (--argc>=0) arg[1] = casadi_from_mex(argv[1], w+4, casadi_s1, w+16);
  if (--argc>=0) arg[2] = casadi_from_mex(argv[2], w+5, casadi_s2, w+16);
  if (--argc>=0) arg[3] = casadi_from_mex(argv[3], w+8, casadi_s1, w+16);
  if (--argc>=0) arg[4] = casadi_from_mex(argv[4], w+9, casadi_s1, w+16);
  if (--argc>=0) arg[5] = casadi_from_mex(argv[5], w+10, casadi_s1, w+16);
  if (--argc>=0) arg[6] = casadi_from_mex(argv[6], w+11, casadi_s1, w+16);
  if (--argc>=0) arg[7] = casadi_from_mex(argv[7], w+12, casadi_s1, w+16);
  --resc;
  res[0] = w+13;
  grad_h_theta_fcn_incref();
  mem = grad_h_theta_fcn_checkout();
  i = grad_h_theta_fcn(arg, res, iw, w+16, mem);
  if (i) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"grad_h_theta_fcn\" failed.");
  grad_h_theta_fcn_release(mem);
  grad_h_theta_fcn_decref();
  if (res[0]) resv[0] = casadi_to_mex(casadi_s3, res[0]);
}
#endif

casadi_int main_grad_h_theta_fcn(casadi_int argc, char* argv[]) {
  casadi_int j;
  casadi_real* a;
  const casadi_real* r;
  casadi_int flag;
  casadi_int *iw = 0;
  casadi_real w[39];
  const casadi_real* arg[10];
  casadi_real* res[2];
  arg[0] = w+0;
  arg[1] = w+4;
  arg[2] = w+5;
  arg[3] = w+8;
  arg[4] = w+9;
  arg[5] = w+10;
  arg[6] = w+11;
  arg[7] = w+12;
  res[0] = w+13;
  a = w;
  for (j=0; j<13; ++j) if (scanf("%lg", a++)<=0) return 2;
  flag = grad_h_theta_fcn(arg, res, iw, w+16, 0);
  if (flag) return flag;
  r = w+13;
  for (j=0; j<3; ++j) CASADI_PRINTF("%g ", *r++);
  CASADI_PRINTF("\n");
  return 0;
}


#ifdef MATLAB_MEX_FILE
void mexFunction(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  char buf[17];
  int buf_ok = argc > 0 && !mxGetString(*argv, buf, sizeof(buf));
  if (!buf_ok) {
    mex_grad_h_theta_fcn(resc, resv, argc, argv);
    return;
  } else if (strcmp(buf, "grad_h_theta_fcn")==0) {
    mex_grad_h_theta_fcn(resc, resv, argc-1, argv+1);
    return;
  }
  mexErrMsgTxt("First input should be a command string. Possible values: 'grad_h_theta_fcn'");
}
#endif
CASADI_SYMBOL_EXPORT int main(int argc, char* argv[]) {
  if (argc<2) {
    /* name error */
  } else if (strcmp(argv[1], "grad_h_theta_fcn")==0) {
    return main_grad_h_theta_fcn(argc-2, argv+2);
  }
  fprintf(stderr, "First input should be a command string. Possible values: 'grad_h_theta_fcn'\nNote: you may use function.generate_input to create a command string.\n");
  return 1;
}
#ifdef __cplusplus
} /* extern "C" */
#endif
